# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-08 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start', models.DateField()),
                ('finish', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active', to='user_app.userReg')),
                ('join', models.ManyToManyField(related_name='joiner', to='user_app.userReg')),
            ],
        ),
    ]
