# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-08 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='event',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='active',
            old_name='finish',
            new_name='fin',
        ),
    ]
