# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-08 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0002_auto_20180308_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active',
            name='fin',
            field=models.TimeField(),
        ),
    ]
